jwtSecret: libraryTest
jwtExpiration: 1800000

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: library-authorization
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: UNITTEST
  jpa:
    show-sql: true
